version: '3.7'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  placement:
    image: "daprio/dapr:latest"
    command: ["./placement"]
    ports:
      - "6050:6050"

  taskmicroservice:
    build:
      context: .
      dockerfile: TaskMicroservice/Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis
      - zipkin
      - placement
    networks:
      - dapr-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=taskmicroservice"
      - "dapr.io/app-port=80"
      - "dapr.io/app-protocol=http"

  remindermicroservice:
    build:
      context: .
      dockerfile: ReminderMicroservice/Dockerfile
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis
      - placement
    networks:
      - dapr-network
    volumes:
      - ./components:/components
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=remindermicroservice"
      - "dapr.io/app-port=80"
      - "dapr.io/app-protocol=http"

  blazorfrontendtodo:
    build:
      context: .
      dockerfile: BlazorFrontendTodo/Dockerfile
    ports:
      - "7002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - taskmicroservice
      - remindermicroservice
    networks:
      - dapr-network

  identitymanager:
    build:
      context: .
      dockerfile: IdentityManager/Dockerfile
    ports:
      - "7003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge
