version: '3.7'

services:
  redis:
    image: "redis:alpine" # Uses the redis-alpine image to minimize size
    ports:
      - "6379:6379" # Maps port 6379 on the host to port 6379 on the container

  taskmicroservice:
    build:
      context: . # Context for build is the current directory
      dockerfile: TaskMicroservice/Dockerfile # Specifies the Dockerfile for TaskMicroservice
    ports:
      - "7000:80" # Maps port 7000 on the host to port 80 on the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis # Indicates that taskmicroservice depends on redis
    networks:
      - dapr-network # Specifies the network for taskmicroservice
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=taskmicroservice"
      - "dapr.io/app-port=80"
      - "dapr.io/app-protocol=http"

  remindermicroservice:
    build:
      context: . # Context for build is the current directory
      dockerfile: ReminderMicroservice/Dockerfile # Specifies the Dockerfile for ReminderMicroservice
    ports:
      - "7001:80" # Maps port 7001 on the host to port 80 on the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis # Indicates that remindermicroservice depends on redis
    networks:
      - dapr-network # Specifies the network for remindermicroservice
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=remindermicroservice"
      - "dapr.io/app-port=80"
      - "dapr.io/app-protocol=http"

  blazorfrontendtodo:
    build:
      context: . # Context for build is the current directory
      dockerfile: BlazorFrontendTodo/Dockerfile # Specifies the Dockerfile for BlazorFrontendTodo
    ports:
      - "7002:80" # Maps port 7002 on the host to port 80 on the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - taskmicroservice # Indicates dependencies
      - remindermicroservice
      - redis
    networks:
      - dapr-network # Specifies the network for BlazorFrontendTodo
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=blazorfrontendtodo"
      - "dapr.io/app-port=80"
      - "dapr.io/app-protocol=http"

networks:
  dapr-network:
    driver: bridge # Uses the bridge driver for networking
